if status is-interactive
    set -g fish_greeting
    starship init fish | source
    set -gx SUDO_EDITOR "subl -w"
function wal-smart
    if test (count $argv) -eq 0
        return 1
    end
    set img_path (realpath "$argv[1]")
    walrs -i "$img_path"
    while not test -f ~/.cache/wal/colors.sh
        sleep 0.05
    end
    sleep 0.1
    cp ~/.cache/wal/colors-waybar.css ~/.config/waybar/colors/wal.css
    sed -i "s|exec-once = walrs -n -i.*|exec-once = walrs -n -i $img_path|" ~/.config/hypr/hyprland.conf
    sed -i "s|exec-once = awww img.*|exec-once = awww img \"$img_path\" --transition-type none|" ~/.config/hypr/hyprland.conf
    if not pgrep -x awww-daemon >/dev/null
        awww-daemon &
        sleep 0.5
    end
    awww img "$img_path" --transition-type random --transition-step 90 --transition-fps 60
    set color5 (grep "color5='" ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set color8 (grep "color8='" ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    if test -n "$color5"
        printf "general {\n    col.active_border = rgb(%s)\n    col.inactive_border = rgb(%s)\n}\n" \
            $color5 $color8 > ~/.config/hypr/colors.conf
        hyprctl reload >/dev/null 2>&1 &
    end
    # --- FOOT COLORS ---
    set bg (grep "background='" ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set fg (grep "foreground='" ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c0  (grep "color0='"  ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c1  (grep "color1='"  ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c2  (grep "color2='"  ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c3  (grep "color3='"  ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c4  (grep "color4='"  ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c5  (grep "color5='"  ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c6  (grep "color6='"  ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c7  (grep "color7='"  ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c8  (grep "color8='"  ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c9  (grep "color9='"  ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c10 (grep "color10='" ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c11 (grep "color11='" ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c12 (grep "color12='" ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c13 (grep "color13='" ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c14 (grep "color14='" ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    set c15 (grep "color15='" ~/.cache/wal/colors.sh | cut -d"'" -f2 | tr -d "#")
    printf "[colors-dark]\nalpha=0.75\nbackground=%s\nforeground=%s\nregular0=%s\nregular1=%s\nregular2=%s\nregular3=%s\nregular4=%s\nregular5=%s\nregular6=%s\nregular7=%s\nbright0=%s\nbright1=%s\nbright2=%s\nbright3=%s\nbright4=%s\nbright5=%s\nbright6=%s\nbright7=%s\n" \
        $bg $fg $c0 $c1 $c2 $c3 $c4 $c5 $c6 $c7 $c8 $c9 $c10 $c11 $c12 $c13 $c14 $c15 \
        > ~/.config/foot/colors-foot.ini
    # --- WAYBAR / SWAYNC ---
    pkill waybar
    waybar >/dev/null 2>&1 &
    pkill swaync
    sleep 0.3
    swaync >/dev/null 2>&1 &
    # --- HYPRLOCK ---
    mkdir -p ~/.config/hypr/wallpapers
    ln -sf "$img_path" ~/.config/hypr/wallpapers/lockscreen.jpg
    # --- WLOGOUT COLORS ---
    mkdir -p ~/.config/wlogout
    set bg2 (grep "background='" ~/.cache/wal/colors.sh | cut -d"'" -f2)
    set wc5 (grep "color5='" ~/.cache/wal/colors.sh | cut -d"'" -f2)
    set wc7 (grep "color7='" ~/.cache/wal/colors.sh | cut -d"'" -f2)
    set wc8 (grep "color8='" ~/.cache/wal/colors.sh | cut -d"'" -f2)
    printf "/* autogenerated by wal */\n\
@define-color bg rgba(3, 3, 3, 0.85);\n\
@define-color button-bg %s;\n\
@define-color button-border %s;\n\
@define-color text %s;\n\
\n\
@define-color hover-bg %s;\n\
@define-color hover-border %s;\n\
@define-color hover-text #ffffff;\n\
\n\
@define-color active-bg %s;\n\
@define-color active-border %s;\n\
@define-color active-text #ffffff;\n" \
        $bg2 $wc8 $wc7 \
        $wc5 $wc7 \
        $wc7 $wc5 \
        > ~/.config/wlogout/colors.css
    # --- WLOGOUT ICON RECOLOR ---
    set icon_color $wc5
    for icon in lock shutdown reboot suspend
        magick ~/.config/wlogout/icons/$icon.png \
            -alpha on -fill "$icon_color" -colorize 100% \
            ~/.config/wlogout/icons/$icon.png
    end
end
function rofi-wallpaper
    set wall_dir ~/wallpapers
    set selected (ls $wall_dir | while read -l img
        echo -en "$img\0icon\x1f$wall_dir/$img\n"
    end | rofi -dmenu -i -p "Wallpapers" -show-icons -theme-str 'listview { columns: 3; lines: 3; } element { orientation: vertical; } element-icon { size: 120px; }')
    if test -n "$selected"
        wal-smart "$wall_dir/$selected"
    end
end
# Быстрые команды для управления zapret
alias zapret-config="$HOME/zapret-configs/install.sh"
alias zapret-utils="$HOME/zapret-configs/utils-zapret.sh"
# Пути
fish_add_path $HOME/.local/bin
end
# быстрые команды для управления zapret
